### ISSUE TITLE
Material Stack Dupe

### ISSUE THREAD

**Issue by Andrew-Fall** [Persistent-SS13/Persistent-Bay#1233]
If you take materials from a stack they become steel sheets, (1 sheet of quartz from a stack of quartz became 1 sheet of steel).

**Comment by PsyCommando** [comment]
I couldn't reproduce that. I get the feeling people mean the weird stack reinforcing feature that bay added. So you can turn material stacks into reinforced material stacks by using a material stack on another stack of another type, and it drops a reinforced stack if the material is harder than the source one. 

Another side issue to this is that for some really dumb reasons some piece of code creates its own subtype of `/obj/item/stack/material', the `/obj/item/stack/material/generic` type. Since stack merging is determined by type and not material, this makes stacks of similar materials not merge and try to reinforce eachothers instead.
