### ISSUE TITLE
Printed Gun issues.

### ISSUE THREAD

**Issue by Andrew-Fall** [Persistent-SS13/Persistent-Bay#1236]
Printed guns do no (or minimal) damage. They also sometimes only fire when they have one shell loaded. Some bugs appear to be associated with being on a space turf.
https://cdn.discordapp.com/attachments/592766002232557627/594371734568697866/unknown.png

**Comment by PsyCommando** [comment]
Do we have any actual proof that guns do no damage? 
I think most people don't realize guns have been severely nerfed by brawler. The bug with being on a space turf is a different one altogether. 

The actual projectile fails to fire when you're on a space tile, because for some reasons the get_turf made on the player returns garbage in space apparently, and it makes a check in the proc making the projectile fail and return early. So there's no projectile fired or sound played, but bullets are still consumed. Its also partly a design flaw in the way the gun code works I think.

**Comment by PsyCommando** [comment]
Apparently it was literally because someone made code that would straight up delete projectiles in space..
https://github.com/Baystation12/Baystation12/pull/25393

**Comment by Andrew-Fall** [comment]
Psy didn't use Close's #blah
